clear; close all; clc;

%% Output settings
script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

out_dir = fullfile(script_dir, "viability_outputs");
if ~exist(out_dir, "dir")
    mkdir(out_dir);
end

save_figures = true;

%% Colors
color_control = [0.337, 0.706, 0.914];
color_cpa     = [0.800, 0.600, 0.700];
color_cryo    = [0.902, 0.624, 0.000];
color_conv    = [0.600, 0.600, 0.600];

bar_colors = [color_control; color_cpa; color_cryo; color_conv];

conditions = [
    "Control"
    "Spray + CPA Loading/Unloading"
    "Cryoaerosolization + Rewarming"
    "Convective Cooling + Rewarming"
];

cell_types = ["HDF", "RBC", "hiPSCs"];

%% HDF experiment-level values
hdf_replicates = [
    99.16830966 98.76908287 98.80056311 97.85320704 99.07292518 98.82375676;
    97.89044701 91.98385239 95.74955912 96.03024950 93.43877338 96.04715771;
    83.62394763 96.78189850 85.09970996 93.29386282 92.85613684 91.06001655;
     0.36014406  3.13523662  6.31504412 11.69018424  7.96707371 11.20621174
];

hdf_mean = mean(hdf_replicates, 2).';
hdf_sd = std(hdf_replicates, 0, 2).';
hdf_n = [6 6 6 6];

%% RBC experiment-level values
rbc_replicates = [
    98.700000 98.820000 98.580000 98.633333;
    94.252333 95.319167 90.281700 95.633333;
    97.448133 92.391067 93.53333333 NaN;
    84.051000 84.225667 82.59533333 83.876333
];

rbc_mean = mean(rbc_replicates, 2, 'omitnan').';
rbc_error = std(rbc_replicates, 0, 2, 'omitnan').';
rbc_n = sum(isfinite(rbc_replicates), 2).';

%% hiPSC experiment-level values
hipsc_replicates = [
    99.50 99.00 99.75 100.00;
    90.25 95.75 96.75 NaN;
    87.25 96.00 93.50 NaN;
     8.50  4.75  1.50 NaN
];

hipsc_mean = mean(hipsc_replicates, 2, 'omitnan').';
hipsc_sd = std(hipsc_replicates, 0, 2, 'omitnan').';
hipsc_n = sum(isfinite(hipsc_replicates), 2).';

%% Combined plotting arrays
Y = [hdf_mean; rbc_mean; hipsc_mean];

Yerr_lower = [hdf_sd; rbc_error; hipsc_sd];
Yerr_upper = Yerr_lower;

N = [hdf_n; rbc_n; hipsc_n];

replicate_data = {
    hdf_replicates
    rbc_replicates
    hipsc_replicates
};

%% Export summary table
Cell_type = repelem(cell_types.', 4);
Experimental_group = repmat(conditions, 3, 1);

Mean_pct = reshape(Y.', [], 1);
Err_lower_pct = reshape(Yerr_lower.', [], 1);
Err_upper_pct = reshape(Yerr_upper.', [], 1);
n = reshape(N.', [], 1);

Error_bar_description = [
    "SD across six independent experiments"
    "SD across six independent experiments"
    "SD across six independent experiments"
    "SD across six independent experiments"

    "SD across four independent experiments"
    "SD across four independent experiments"
    "SD across three independent experiments"
    "SD across four independent experiments"

    "SD across four independent experiments"
    "SD across three independent experiments"
    "SD across three independent experiments"
    "SD across three independent experiments"
];

summary_table = table( ...
    Cell_type, ...
    Experimental_group, ...
    Mean_pct, ...
    Err_lower_pct, ...
    Err_upper_pct, ...
    n, ...
    Error_bar_description);

writetable( ...
    summary_table, ...
    fullfile(out_dir, "viability_summary_table.csv"));

figure_summary = table( ...
    Cell_type, ...
    Experimental_group, ...
    Mean_pct, ...
    Err_upper_pct, ...
    n, ...
    'VariableNames', ...
    {'CellType', 'Condition', 'MeanViability_pct', 'SD_pct', 'N'});

writetable( ...
    figure_summary, ...
    fullfile(script_dir, "Figure_7_summary.csv"));

%% Statistical comparisons
% Two-sided Welch t-tests on independent experiment-level values.
% Three adjacent comparisons are Holm-adjusted separately within each cell type.

[hdf_p_raw, hdf_p_holm, hdf_sig_labels] = ...
    adjacentWelchHolm(hdf_replicates);

[rbc_p_raw, rbc_p_holm, rbc_sig_labels] = ...
    adjacentWelchHolm(rbc_replicates);

[stem_p_raw, stem_p_holm, stem_sig_labels] = ...
    adjacentWelchHolm(hipsc_replicates);

raw_p = [
    hdf_p_raw;
    rbc_p_raw;
    stem_p_raw
];

adjusted_p = [
    hdf_p_holm;
    rbc_p_holm;
    stem_p_holm
];

sig_table = table( ...
    repelem(cell_types.', 3), ...
    repmat([ ...
        "Control vs condition 2"; ...
        "Condition 2 vs condition 3"; ...
        "Condition 3 vs condition 4"], 3, 1), ...
    reshape(raw_p.', [], 1), ...
    reshape(adjusted_p.', [], 1), ...
    string(reshape( ...
        [hdf_sig_labels; rbc_sig_labels; stem_sig_labels].', ...
        [], 1)), ...
    'VariableNames', { ...
        'CellType', ...
        'Comparison', ...
        'RawP', ...
        'HolmAdjustedP', ...
        'SignificanceLabel'});

writetable( ...
    sig_table, ...
    fullfile(out_dir, "significance_results.csv"));

%% Main combined figure
fig = figure( ...
    'Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [100, 100, 950, 560]);

ax = axes(fig);
hold(ax, 'on');

n_groups = size(Y, 1);
n_bars = size(Y, 2);

group_centers = 1:n_groups;

bar_width = 0.18;
bar_offsets = [-1.5, -0.5, 0.5, 1.5] * bar_width;

bar_handles = gobjects(n_bars, 1);
x_positions = zeros(n_groups, n_bars);

for j = 1:n_bars

    xj = group_centers + bar_offsets(j);
    x_positions(:, j) = xj;

    bar_handles(j) = bar( ...
        ax, ...
        xj, ...
        Y(:, j), ...
        bar_width, ...
        'FaceColor', bar_colors(j, :), ...
        'EdgeColor', [0.25, 0.25, 0.25], ...
        'LineWidth', 0.8);

    errorbar( ...
        ax, ...
        xj, ...
        Y(:, j), ...
        Yerr_lower(:, j), ...
        Yerr_upper(:, j), ...
        'k', ...
        'LineStyle', 'none', ...
        'LineWidth', 1.1, ...
        'CapSize', 7);

    for g = 1:n_groups

        points = replicate_data{g}(j,:);
        points = points(isfinite(points));

        if ~isempty(points)

            if numel(points) == 1
                jitter = 0;
            else
                jitter = linspace(-0.045, 0.045, numel(points));
            end

            scatter( ...
                ax, ...
                xj(g) + jitter, ...
                points, ...
                28, ...
                'k', ...
                'filled', ...
                'HandleVisibility', 'off');
        end
    end
end

yline( ...
    ax, ...
    100, ...
    ':', ...
    'Color', [0.45, 0.45, 0.45], ...
    'LineWidth', 1.0);

add_sig_bars_for_group( ...
    ax, ...
    x_positions(1, :), ...
    Y(1, :), ...
    Yerr_upper(1, :), ...
    hdf_sig_labels, ...
    103.0);

add_sig_bars_for_group( ...
    ax, ...
    x_positions(2, :), ...
    Y(2, :), ...
    Yerr_upper(2, :), ...
    rbc_sig_labels, ...
    103.0);

add_sig_bars_for_group( ...
    ax, ...
    x_positions(3, :), ...
    Y(3, :), ...
    Yerr_upper(3, :), ...
    stem_sig_labels, ...
    103.0);

xlim(ax, [0.45, n_groups + 0.55]);
ylim(ax, [0, 130]);

yticks(ax, 0:20:100);

set( ...
    ax, ...
    'XTick', group_centers, ...
    'XTickLabel', cell_types, ...
    'FontName', 'Arial', ...
    'FontSize', 24, ...
    'LineWidth', 1.1, ...
    'Box', 'on', ...
    'TickDir', 'in');

ax.XAxis.TickLength = [0 0];
ax.YAxis.TickLength = [0 0];

ylabel( ...
    ax, ...
    'Viability (%)', ...
    'FontName', 'Arial', ...
    'FontSize', 24);

grid(ax, 'on');

ax.GridAlpha = 0.22;
ax.YGrid = 'on';
ax.XGrid = 'off';

lgd = legend( ...
    ax, ...
    bar_handles, ...
    conditions, ...
    'NumColumns', 2, ...
    'Box', 'on', ...
    'FontSize', 16, ...
    'Location', 'none');

drawnow;

lgd.Units = 'normalized';
ax.Units = 'normalized';

legend_height = lgd.Position(4);

lgd.Position = [ ...
    ax.Position(1), ...
    ax.Position(2) + ax.Position(4) - legend_height, ...
    ax.Position(3), ...
    legend_height];

lgd.LineWidth = 1.1;

box(ax, 'on');

if save_figures

    exportgraphics( ...
        fig, ...
        fullfile(out_dir, "combined_viability_figure.png"), ...
        'Resolution', 600);

    exportgraphics( ...
        fig, ...
        fullfile(out_dir, "combined_viability_figure.pdf"), ...
        'ContentType', 'vector');
end

%% Local functions

function add_sig_bars_for_group( ...
    ax, xvals, yvals, yerr_upper, labels, base_y)

    xvals = xvals(:).';
    labels = labels(:).';

    y = max( ...
        base_y, ...
        max(yvals + yerr_upper) + 1.2);

    tick_h = 0.8;
    label_offset = 0.55;

    plot( ...
        ax, ...
        [xvals(1), xvals(4)], ...
        [y, y], ...
        'k-', ...
        'LineWidth', 0.9);

    for i = 1:4

        plot( ...
            ax, ...
            [xvals(i), xvals(i)], ...
            [y, y - tick_h], ...
            'k-', ...
            'LineWidth', 0.9);
    end

    for i = 1:3

        text( ...
            ax, ...
            mean([xvals(i), xvals(i + 1)]), ...
            y + label_offset, ...
            labels{i}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontName', 'Arial', ...
            'FontSize', 24);
    end
end

function [rawP, adjustedP, labels] = adjacentWelchHolm(replicates)

    comparisonCount = size(replicates, 1) - 1;

    rawP = zeros(1, comparisonCount);

    for index = 1:comparisonCount

        group1 = replicates(index, :);
        group2 = replicates(index + 1, :);

        group1 = group1(isfinite(group1));
        group2 = group2(isfinite(group2));

        [~, rawP(index)] = ttest2( ...
            group1, ...
            group2, ...
            'Vartype', 'unequal', ...
            'Tail', 'both');
    end

    adjustedP = holmAdjust(rawP);

    labels = arrayfun( ...
        @pValueLabel, ...
        adjustedP, ...
        'UniformOutput', false);
end

function adjustedP = holmAdjust(rawP)

    originalSize = size(rawP);

    rawP = rawP(:);

    comparisonCount = numel(rawP);

    [sortedP, sortOrder] = sort(rawP);

    adjustedSorted = zeros(comparisonCount, 1);

    runningMaximum = 0;

    for index = 1:comparisonCount

        candidate = ...
            (comparisonCount - index + 1) * ...
            sortedP(index);

        runningMaximum = ...
            max(runningMaximum, candidate);

        adjustedSorted(index) = ...
            min(1, runningMaximum);
    end

    adjustedP = zeros(comparisonCount, 1);

    adjustedP(sortOrder) = adjustedSorted;

    adjustedP = reshape( ...
        adjustedP, ...
        originalSize);
end

function label = pValueLabel(pValue)

    if pValue < 0.001
        label = '***';

    elseif pValue < 0.01
        label = '**';

    elseif pValue < 0.05
        label = '*';

    else
        label = 'ns';
    end
end